#
# Copyright Gen Digital Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: Build

env:
  GO_VERSION: 1.21

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run checks
        run: |
          make checks

  unitTest:
    name: Unit test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        id: go

      - uses: actions/checkout@v2

      - name: Run unit test
        timeout-minutes: 15
        run: make unit-test

      - name: Upload coverage to Codecov
        timeout-minutes: 10
        if: matrix.os == 'ubuntu-latest' && github.repository == 'trustbloc/sidetree-svc-go'
        uses: codecov/codecov-action@v1.3.1
        with:
          file: ./coverage.txt
